/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { GoalEntryStatus, ScheduleType } from "@/types/enums";
import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

// ! Selectable timestamps should actually just be date, but because of edge case
// ! where jsonArrayFrom serializes Dates to strings, I've manually adjusted this type for now
// ! https://github.com/kysely-org/kysely/issues/482
export type Timestamp = ColumnType<Date | string, Date | string, Date | string>;

export interface Goal {
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string;
  id: string;
  partnerEmail: string;
  scheduleDays: number[] | null;
  scheduleType: ScheduleType;
  stakeAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface GoalEntry {
  createdAt: Generated<Timestamp>;
  dueAt: Timestamp;
  goalId: string;
  id: string;
  partnerVerificationToken: string | null;
  partnerVerificationTokenExpiresAt: Timestamp | null;
  partnerVerifiedAt: Timestamp | null;
  status: GoalEntryStatus;
  updatedAt: Generated<Timestamp>;
  userVerificationToken: string | null;
  userVerificationTokenExpiresAt: Timestamp | null;
  userVerifiedAt: Timestamp | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  firstName: string;
  id: string;
  lastName: string | null;
  password: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  goal: Goal;
  goalEntry: GoalEntry;
  user: User;
}
