/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Goal {
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  description: string;
  id: string;
  partnerEmail: string;
  scheduleDays: number[] | null;
  scheduleType: string;
  stakeAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface GoalEntry {
  createdAt: Generated<Timestamp>;
  dueAt: Timestamp;
  goalId: string;
  id: string;
  partnerVerifiedAt: Timestamp | null;
  status: string;
  updatedAt: Generated<Timestamp>;
  userVerifiedAt: Timestamp | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  goal: Goal;
  goalEntry: GoalEntry;
  user: User;
}
